### DISCUSSION TITLE
How to translate to MyST a reST configuration involving `rst_prolog` role, JS and CSS?

### DISCUSSION THREAD

**Discussion by dbitouze** [executablebooks/MyST-Parser#634] [Q&A]
Trying to replicate with `MyST` a `reST` configuration involving `rst_prolog` role, `JS` and `CSS`, I'm a bit lost between roles and substitutions. 

Could someone help me to translate to `MyST` the following `reST` configuration? Thanks in anticipation.

1. My `conf.py` file contains:
```Python
rst_prolog = """
.. role:: latexlogo
"""
```
2. A `source/_static/js/custom.js` file contains:
```javascript
window.onload = function() {
    var latexlogos = document.querySelectorAll('.latexlogo'), i, j;

    for (i = 0; i < latexlogos.length; ++i) {
        let insidelatexlogo = '';
        for (j = 0; j < latexlogos[i].innerText.length; j++) {
            if (latexlogos[i].innerText[j] !== " ") {
                insidelatexlogo += "<insidelatexlogo>";
                insidelatexlogo += latexlogos[i].innerText[j];
                insidelatexlogo += "</insidelatexlogo>";
            }
        }
        latexlogos[i].innerHTML = insidelatexlogo;
    }

};
```
3. A `source/_static/css/custom.css` file contains:
```css
insidelatexlogo:nth-child(2) {
    text-transform: uppercase;
    font-size: 0.85em;
    vertical-align: 0.15em;
    margin-left: -0.36em;
    margin-right: -0.15em;
}

insidelatexlogo:nth-child(4) {
    text-transform: uppercase;
    font-size: 1em;
    vertical-align: -0.25ex;
    margin-left: -0.1667em;
    margin-right: -0.125em;
}
```
