### DISCUSSION TITLE
Convert domain from rst to myst

### DISCUSSION THREAD

**Discussion by mosabua** [executablebooks/MyST-Parser#794] [Q&A] [answered]
I am currently converting the Trino docs from rst to myst with rst2myst. One thing I stumbled into now is a whole lot of `.. function::` and related `:func:` content. What is the equivalent correct syntax in myst?

The converter just wraps this all into eval-rst blocks and that is suboptimal and has a bunch of other issues I then run into.

And related question .. the current setup is basically using the Python domain .. but thats technically wrong. Ideally it could be generic or otherwise a SQL domain .. but not such thing exists as far as I am aware.

**Comment by chrisjsewell** [comment, marked as answer]
> And related question .. the current setup is basically using the Python domain .. but thats technically wrong. Ideally it could be generic or otherwise a SQL domain .. but not such thing exists as far as I am aware.

Heya, you can use `rst2myst convert --default-domain py` to specify the default domain, which relates to https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-primary_domain

If your `function` relate to the Python domain, then you can use `rst2myst convert --conversions conv.yml test.rst`, where `conv.yml` looks like:

```yaml
sphinx.domains.python.PyFunction: direct
sphinx.domains.python.PyVariable: direct
sphinx.domains.python.PyClasslike: direct
sphinx.domains.python.PyMethod: direct
sphinx.domains.python.PyClassMethod: direct
sphinx.domains.python.PyStaticMethod: direct
sphinx.domains.python.PyAttribute: direct
sphinx.domains.python.PyModule: direct
```

Note, make sure to upgrade rst-to-myst to v0.4.0
