### ISSUE TITLE
Usage with RTD - sphinx>=2 requirement was optional?

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/MyST-Parser#139]
Read the docs is a bit messy to work with sometimes, because it comes with sphinx<2 pre-installed, so when we run `pip install -r doc-requirements.txt` it will settle for version 1 unless a dependency forces is to go higher.

But, it seems MyST-Parser have a hard dependency of sphinx>1 due to the following error:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/zero-to-jupyterhub/envs/latest/lib/python3.7/site-packages/myst_parser/sphinx_renderer.py", line 16, in <module>
    from sphinx.project import Project
```

Due to this, I suggest to add the requirement of sphinx >=2 directly in MyST-Parser.

### doc-requirements.txt
```
pydata_sphinx_theme
pyyaml
myst_parser
sphinx-autobuild
sphinx-copybutton
sphinx<3
```

### .readthedocs.yml
```yaml
# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/zero-to-jupyterhub/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required (RTD configuration version)
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    # WARNING: This requirements file will be installed without the pip
    #          --upgrade flag in an existing environment. This means that if a
    #          package is specified without a lower boundary, we may end up
    #          accepting the existing version.
    #
    #          ref: https://github.com/readthedocs/readthedocs.org/blob/0e3df509e7810e46603be47d268273c596e68455/readthedocs/doc_builder/python_environments.py#L335-L344
    - requirements: doc/doc-requirements.txt

```
