### ISSUE TITLE
`literalinclude` does not work as expected with `start-after` and `end-before` keys

### ISSUE THREAD

**Issue by rozsasarpi** [executablebooks/MyST-Parser#308]
**Describe the bug**

When the `start-after` and `end-before` keys are used in the `literalinclude` directive, they seem to be disregarded and the full content of the file is included.

**To Reproduce**

Using this code will include the full content of `example.py` in the generated html page (`make html`) although it should not:

    ```{literalinclude} example.py
    ---
    language: python
    start-after: # Import packages
    end-before: # Input data
    ---
    ```

The content of `example.py`:

```python
# Import packages
import os
import time

# Input data
a = 1
b = 2
```

If I use the `eval-rst` directive it works and only the desired code segment is included:

    ```{eval-rst}
    .. literalinclude:: examples.py
        :start-after: # Import packages
        :end-before: # Input data
    ```

**Expected behavior**

It is expected that the `MyST` `literalinclude` directive produced the same output as that of `reST`. Considering the used example this code snippet is expected to be included in the generated html page:

```python
# Import packages
import os
import time

```

**Environment**

- Python Version: 3.7.2
- Package versions: 0.13.3
- Operating System: Windows 10

**Comment by chrisjsewell** [comment]
```yaml
language: python
start-after: # Import packages
end-before: # Input data
```

Is parsed as YAML, so you need to put quotes around the text, otherwise it will treat them as comments

```yaml
language: python
start-after: "# Import packages"
end-before: "# Input data"
```
