### ISSUE TITLE
amsmath label is not aligning to right end

### ISSUE THREAD

**Issue by wzleong** [executablebooks/MyST-Parser#643]
Adding equation in markdown with labels with referencing. 
Below is the code.
$$
\begin{split}
x = y+z
\end{split}
$$ (eqn:coordinate)

The label unfortunately is generated as shown below at the left of the equation instead of aligning to right end. 
This is generated with sphinx, sphinx_rtd_theme. The equations were also initially aligning to the right but have resolved it but adding the custom css. Please advise if there is a way to update the label to align at the right
.math {
    margin-left: auto !important;
    margin-right: auto !important;
    width: fit-content !important;
    text-align: right !important;
}

![image](https://user-images.githubusercontent.com/20381221/198838777-f71d650a-1e1d-4604-912c-b0e3074cc643.png)

**Comment by IvolgaDmitriy** [comment]
@wzleong , 
I don't know how relevant it is, but this problem may be related to the theme used. For example https://github.com/readthedocs/sphinx_rtd_theme/pull/383 . 
My own style helped me (for sphinx-rtd-theme):
```css
.eqno {
    margin-left: 5px;
    float: right;
}
.math .headerlink {
    display: none;
    visibility: hidden;
}
.math:hover .headerlink {
    display: inline-block;
    visibility: visible;
    margin-right: -0.7em;
}
```
