### ISSUE TITLE
Table cell alignment classes are incompatible with bootstrap 5

### ISSUE THREAD

**Issue by jhcole** [executablebooks/MyST-Parser#785]
The "left" and "right" cell alignment options are handled by assigning `text-left` or `text-right` classes to the cell.  I think this approach was relying on the styling of these classes in bootstrap, but bootstrap 5 removed these classes and replaced them with `text-start` and `text-end`.  I'm guessing this was done to support right-to-left languages.  The problem is currently visible in the [MyST parser documentation](https://myst-parser.readthedocs.io/en/latest/syntax/tables.html#markdown-syntax).

![image](https://github.com/executablebooks/MyST-Parser/assets/1099507/049abd88-260f-41c3-b612-9f3704139898).

For a Jupyter book, I've worked around the issue by adding
```yaml
sphinx:
  config:
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
```
to `_config.yml`, and then adding 
```css
.text-left{
  text-align: left !important;
}
.text-right{
  text-align: right !important;
}
```
to `_static/custom.css`.
