### ISSUE TITLE
`\(...\)` and `\[...\]` not working as expected

### ISSUE THREAD

**Issue by dbitouze** [executablebooks/MyST-Parser#817]
### What version of `myst-parser` are you using?

2.0.0

### What version dependencies are you using?

`sphinx`

### What operating system are you using?

Linux

### Describe the Bug

The documentation claims [`\(...\)`](https://myst-parser.readthedocs.io/en/latest/syntax/reference.html#extended-inline-tokens) and [`\[...\]`](https://myst-parser.readthedocs.io/en/latest/syntax/reference.html#block-multi-line-tokens) should give the same result as `$...$` and `$$...$$`. But that's not the case: the render is as `(...)` and `[...]`.

### Expected Behavior

As claimed by the documentation:

- `\(\mathrm{e}^{\mathrm{i}\pi}+1=0\)` should behave as `$\mathrm{e}^{\mathrm{i}\pi}+1=0$`
- `\[\mathrm{e}^{\mathrm{i}\pi}+1=0\]` should behave as `$$\mathrm{e}^{\mathrm{i}\pi}+1=0$$`

### To Reproduce

 On the [Live Preview](https://myst-parser.readthedocs.io/en/latest/live-preview.html) page, use e.g. the following configuration `yaml` code:
```yaml
myst_enable_extensions:
- colon_fence
- deflist
- dollarmath
- amsmath
- attrs_inline
- colon_fence
- deflist
- dollarmath
- fieldlist
- html_admonition
- html_image
- replacements
- smartquotes
- strikethrough
- substitution
- tasklist
myst_heading_anchors: 2
myst_highlight_code_blocks: true
```
and the following input text:
```markdown
$\mathrm{e}^{\mathrm{i}\pi}+1=0$

\(\mathrm{e}^{\mathrm{i}\pi}+1=0\)

$$\mathrm{e}^{\mathrm{i}\pi}+1=0$$

\[\mathrm{e}^{\mathrm{i}\pi}+1=0\]
```
You'll see that the raw output is:
```html
<p><span class="formula"><span class="mathrm">e</span><sup><span class="mathrm">i</span><i>π</i></sup> + 1 = 0</span></p>
<p>(\mathrm{e}^{\mathrm{i}\pi}+1=0)</p>
<div class="formula">
<span class="mathrm">e</span><sup><span class="mathrm">i</span><i>π</i></sup> + 1 = 0
</div>
<p>[\mathrm{e}^{\mathrm{i}\pi}+1=0]</p>
```
that is the following HTML render:

<p><span class="formula"><span class="mathrm">e</span><sup><span class="mathrm">i</span><i>π</i></sup> + 1 = 0</span></p>
<p>(\mathrm{e}^{\mathrm{i}\pi}+1=0)</p>
<div class="formula">
<span class="mathrm">e</span><sup><span class="mathrm">i</span><i>π</i></sup> + 1 = 0
</div>
<p>[\mathrm{e}^{\mathrm{i}\pi}+1=0]</p>
